name: Auto Push Updates

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:  

jobs:
  update-repo:
    runs-on: ubuntu-latest 

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2  

     
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

     
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  

      - name: Run script to update GitHub data
        run: python update_prices.py  
          
      - name: Commit and push updates
        run: |
          git config --global user.name "mahkia89"  
          git config --global user.email "mahkiagolbashi@gmail.com" 
          git add .  # add all changes to staging area
          git commit -m "Automated update"  
          git push 

        env:
          TOKEN: ${{ secrets.TOKEN }}
